developing points: 1.delete module 'whatwg-fetch'.update typescript version and use typescript built-in 'fetch' module. 2.delete code '{...this.props}' in 'buttonComponent.tsx',because typescript v2.3.0-dev after.Only in the HTMLProps the properties just valid.Ohterwise typescript will build failed. for example: ERROR in ./src/js/components/buttonComponent.tsx (22,25): error TS2322: Type '{ onClick: () => void; handler: Function; btnName: string; children?: ReactNode; className: "bt n"...' is not assignable to type 'HTMLProps<HTMLButtonElement>'.   Property 'handler' does not exist on type 'HTMLProps<HTMLButtonElement>'.
delete "{...this.props}"